dist: xenial
language: java
install: true
script:
  - mvn clean package
  - mvn clean verify
  - mvn clean deploy
  - travis_wait mvn install 

before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  except:
    - gh-pages
  
jobs:
  include:
    - stage: build
      name: build
      os: linux
      script: mvn package
    - script: mvn site
      name: generate site
    - stage: test 
      name: "Java 8" 
      os: linux
      jdk: openjdk8
      script: mvn test
    - script: mvn test
      name: "Java 11"
      os: linux
      jdk: openjdk11
    - stage: deploy
      name: "deploy"
      script: mvn deploy
      before_script:
        - java -jar target/dropwizard-example-2.0.3-SNAPSHOT.jar db migrate example.yml
        - java -jar target/dropwizard-example-2.0.3-SNAPSHOT.jar server example.yml &
    - script: ./gendoc.sh
      name: "deploy documentation"
      before_script:
        - chmod +x gendoc.sh




 
env:
  global:
    - secure: T627dIuLFGEOK6qgcd7MGucRm6wbme4cTV0yArC2O3kz8IYOJdtuLoymx63LHxkzPlxVzQZVeplZMyrmVCXVtMvn6KiNNZnJ7J3BPesn7+ap/dKwBtC7rG7ihy+QXqJ+gbWKZ4LkPESHOwUV33lCcRJ4oO163dC7LQysiD3PdySwuOG2Y73o1c7OuFpcK3M1+L6tCDGaLfWQzoS5zcLCnMj7miIL+cOl872Y9iGfRG6ngcuheOW8XawaC8Ms3OOk6JhP0W8uQGfSwy8aDsptO7UsjxStymX0bSOyC0r62A++0UA4Og75ILM0k7gf0cXvNHd/uQkaZV/efuSo2Jk1oVTCg6sCLa0sxHTI3b3g9wzS/jDsjaHpbjacgno/1BrK9m1hpC4CLjG+J/cJddNk05LvTALAQ3nktb+49mhtMs/WUiMAT2f2FeyVoKSwp8x9Fizdxq/goxNtpScVn3PnMPpIp5nY7g7z2o1QB4SUMqM5SSefuCUrpDoCcKLpI7qh+/nqasah7KZeO2CkpOnTYNfRniIQMAaoRTA8Sih2uAA5IIjpLHtiX6uUoNNW5kuP6sR6jhqupR9vQWzmR5knYoluYRKKhbRD7m/bba0oB1xOHTe4WNhI+ClWt9Gi8G3tmem0BefZi+6bpWWdpGj3cO2ULiJmJlCwyFwT4WcoGUw=
    - secure: Qwo+BhZUtBy14Iou5QuFytT2WBoTT241mwC3z9Y05MaSl2lqSzgRccNmSyVHJ1YT7PJf6OFXhg7ef7CJ+C4SNGkb/bDhF3XnAb1CgV28sN6XiP51Lx4iO9ZxmVYbis+zScuR9rrvJQOX9YUuaAW2lVcefpRnmqwM7pBf1+cZ9AQ=
