dist: xenial
language: java
install: true
script:
- mvn clean package
- mvn clean verify
- mvn clean deploy
- travis_wait mvn install


  


before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  
jobs:
  include:
    - stage: build
      name: build
      os: linux
      script: mvn package
    - stage: test 
      name: "Java 8" 
      os: linux
      jdk: openjdk8
      script: mvn test
    - script: mvn test
      name: "Java 11"
      os: linux
      jdk: openjdk11
    - stage: deploy
      name: "deploy"
      script: 
        - java -jar target/dropwizard-example-2.0.3-SNAPSHOT.jar db migrate example.yml
        - java -jar target/dropwizard-example-2.0.3-SNAPSHOT.jar server example.yml &
    - script: ./gendoc.sh
        name: "generate and deploy documentation"
        branches:
          except:
            - gh-pages


 
env:
  global:
    - secure: Z9V8PgH+IUG7nTz8K9rvViYobxXkp/N59adcw+8+rwCRvU7Lq/nX02XUR91H5PKoLUjPQEJDINU+CtsMSZxRA+5bTTWPl4qLYUDeFm8G85JIj8QKAiEivu9+D0pxD8RbiPIGz5vhaIbgg9OqzUoScFq6T//AccBUW5GIRU7kIqM=
