sudo: true
dist: xenial
language: java
addons:
  apt:
    packages:
      - ant

jobs:
  include:
    - stage: test
      name: Linux + OpenJDK 8
      os: linux
      dist: xenial
      sudo: required
      jdk: openjdk8
      install: true
      script: src/test/java/com/example/helloworld/IntegrationTest.java
      before_install:
        - chmod +x src/test/java/com/example/helloworld/IntegrationTest.java
        - ./mvnw package
        - java -jar target/dropwizard-example-$DW_VERSION.jar db migrate example.yml
        - java -jar target/dropwizard-example-$DW_VERSION.jar server example.yml
    - stage: test
      name: Linux + Oracle JDK 11
      os: linux
      dist: xenial
      sudo: required
      jdk: openjdk11
      install: true
      script: src/test/java/com/example/helloworld/IntegrationTest.java
    - stage: "Tests Integration"
      name: "Integration Tests Java 8"
      script: ./src/test/java/com/example/helloworld/IntegrationTest.java
    - stage: deploy
      name: "Deploy"
      script: ./deploy
