dist: xenial
language: java
addons:
  apt:
    packages:
      - ant
deploy:
  provider: script
  script: bash scripts/deploy.sh production $TRAVIS_TAG
  on:
    tags: true
    all_branches: true
jdk:
  - openjdk8
template: Hello, %s!
defaultName: Stranger

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/test-example

server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: './logs/application.log'
      archivedLogFilenamePattern: './logs/application-%d-%i.log.gz'
      archive: true
      archivedFileCount: 7
      maxFileSize: '1MiB'

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: src/test/java/com/example/helloworld/resources
    - script: ./src/test/java/com/example/helloworld/IntegrationTest.java
      name: "Integration Tests"     # names the second Tests stage job
    - stage: deploy
      name: "Deploy to GCP"
      script: ./deploy
